#ifndef MODULE_COMMON_H
#define MODULE_COMMON_H

#include "ibm.h"
#include "cpu.h"
#include "model.h"
#include "io.h"
#include "mouse.h"

#include "82091aa.h"
#include "acc2168.h"
#include "acc3221.h"
#include "acer386sx.h"
#include "ali1429.h"
#include "cbm_io.h"
#include "cmd640.h"
#include "compaq.h"
#include "cs8230.h"
#include "dells200.h"
#include "device.h"
#include "cassette.h"
#include "dma.h"
#include "fdc.h"
#include "fdc37c665.h"
#include "fdc37c93x.h"
#include "gameport.h"
#include "ide.h"
#include "intel_flash.h"
#include "keyboard_at.h"
#include "keyboard_olim24.h"
#include "keyboard_pcjr.h"
#include "keyboard_xt.h"
#include "mem.h"
#include "mouse_ps2.h"
#include "nmi.h"
#include "nvr.h"
#include "pci.h"
#include "pic.h"
#include "pit.h"
#include "scamp.h"
#include "serial.h"
#include "sio.h"
#include "sis496.h"
#include "sl82c460.h"
#include "sound_ps1.h"
#include "sound_pssj.h"
#include "sound_sn76489.h"
#include "superxt.h"
#include "sst39sf010.h"
#include "tandy_eeprom.h"
#include "tandy_rom.h"
#include "vid_pcjr.h"
#include "vid_tandy.h"
#include "vid_t1000.h"
#include <pcem/devices.h>
void xt_init();
void pcjr_init();
void tandy1k_init();
void tandy1ksl2_init();
void at_init();
void ibm_at_init();
void at_sis496_init();
void compaq_xt_init();

#endif /* MODULE_COMMON_H */
