set(PCEM_PRIVATE_API ${PCEM_PRIVATE_API}
        ${CMAKE_SOURCE_DIR}/includes/private/models/dma.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/model.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/nmi.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/pic.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/pit.h
        ${CMAKE_SOURCE_DIR}/includes/private/models/serial.h
        )

set(PCEM_SRC ${PCEM_SRC}
        models/dma.c
        models/model.c
        models/nmi.c
        models/nvr_tc8521.c
        models/pic.c
        models/pit.c
        models/serial.c
        models/module/amixt.c
        models/module/ataripc3.c
        models/module/bull_micral_45.c
        models/module/cbm_pc10.c
        models/module/compaq_pii.c
        models/module/compaq_pip.c
        models/module/deskpro.c
        models/module/dtk.c
        models/module/epson_pcax.c
        models/module/epson_pcax2e.c
        models/module/epson_pcax3.c
        models/module/genxt.c
        models/module/ibmat.c
        models/module/ibmpc.c
        models/module/ibmpcjr.c
        models/module/ibmxt.c
        models/module/ibmxt286.c
        models/module/jukopc.c
        models/module/ledge_modelm.c
        models/module/ncr_pc4i.c
        models/module/pxxt.c
        models/module/sis496.c
        models/module/super16t.c
        models/module/super16te.c
        models/module/tandy.c
        models/module/tandy1000hx.c
        models/module/tandy1000sl2.c
        models/module/to16_pc.c
        models/module/tulip_tc7.c
        )